name: Atualizar estrelas no perfil

on:
  schedule:
    - cron: '0 0 * * *'  # Todos os dias à meia-noite
  workflow_dispatch:     # Permite execução manual

permissions:
  contents: write

jobs:
  update-stars:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install requests

    - name: Rodar script de atualização
      run: python scripts/update_stars.py

    - name: Commit e push se houver alterações
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Atualizar número de estrelas ⭐ automaticamente" || echo "Sem mudanças"
        git push
